"""Committee package for Apex Oracle Bot ensemble decision system."""

from src.ood_discriminator import (
    OODDiscriminator,
    TemporalEMASmoother,
    build_ood_state_vector,
    check_ood_and_override,
    get_ood_discriminator,
    reset_ood_discriminator,
)

from .batch_ensemble import (
    BatchEnsembleDropout,
    BatchEnsembleLayerNorm,
    BatchEnsembleLinear,
    BatchEnsembleTransformer,
    convert_model_to_batchensemble,
    replace_linear_with_batchensemble,
)
from .bayesian_transformer import (
    BayesianTransformerBrain,
    EnsemblePrediction,
    bayesian_transformer_brain,
    compute_ece,
    get_bayesian_transformer,
    save_calibration,
    train_temperature_scaling,
)
from .decision_gate import (
    GateResult,
    check_decision_source_gate,
    get_gate_status_summary,
    log_gate_status,
)
from .decision_transformer import (
    DecisionTransformer,
    DTConfig,
    build_action_vector,
    build_state_vector,
    encode_brain_votes,
    encode_features,
    encode_regime,
    get_decision_transformer,
    run_decision_transformer,
    train_decision_transformer,
)
from .hierarchical_skills import (
    HierarchicalSkills,
    OptionsCriticTrainer,
    SkillConfig,
    SkillCritic,
    SkillEncoder,
    SkillLSTMExecutor,
    TerminationHead,
    get_hierarchical_skills,
    get_skills_trainer,
    reset_hierarchical_skills,
    run_hierarchical_skills,
)

__all__ = [
    "BatchEnsembleDropout",
    "BatchEnsembleLayerNorm",
    "BatchEnsembleLinear",
    "BatchEnsembleTransformer",
    "BayesianTransformerBrain",
    "DTConfig",
    "DecisionTransformer",
    "EnsemblePrediction",
    "GateResult",
    "HierarchicalSkills",
    "OODDiscriminator",
    "OptionsCriticTrainer",
    "SkillConfig",
    "SkillCritic",
    "SkillEncoder",
    "SkillLSTMExecutor",
    "TemporalEMASmoother",
    "TerminationHead",
    "bayesian_transformer_brain",
    "build_action_vector",
    "build_ood_state_vector",
    "build_state_vector",
    "check_decision_source_gate",
    "check_ood_and_override",
    "compute_ece",
    "convert_model_to_batchensemble",
    "encode_brain_votes",
    "encode_features",
    "encode_regime",
    "get_bayesian_transformer",
    "get_decision_transformer",
    "get_gate_status_summary",
    "get_hierarchical_skills",
    "get_ood_discriminator",
    "get_skills_trainer",
    "log_gate_status",
    "replace_linear_with_batchensemble",
    "reset_hierarchical_skills",
    "reset_ood_discriminator",
    "run_decision_transformer",
    "run_hierarchical_skills",
    "save_calibration",
    "train_decision_transformer",
    "train_temperature_scaling",
]
