"""Advanced Committee Aggregator Engine.

Features:
1. Dynamic Regime-Adaptive Weight Allocation Matrix.
2. Vote Disagreement Entropy Calculation & Confidence Penalty.
3. Dynamic Position Sizing Multiplier (Kelly-inspired Confidence Sizing: 0.5x to 1.75x).
4. Hard Veto Sentinel Filter.
"""

import asyncio
import json
import math
import os
import time
import uuid
from collections import defaultdict
from typing import Any

from src.alerting import AlertingEngine
from src.config import settings
from src.logging_config import get_logger
from src.ood_discriminator import check_ood_and_override, get_ood_discriminator

from .adaptive_meta import AdaptiveMetaLearner
from .decision_gate import check_decision_source_gate
from .decision_transformer import run_decision_transformer
from .llm_brain import llm_brain
from .models import BrainVote, CommitteeResult
from .momentum_brain import momentum_brain
from .quant_brain import quant_brain
from .rl_meta import RLMetaLearner
from .sentinel_brain import sentinel_brain
from .transformer_brain import transformer_brain

logger = get_logger("committee")

# Alerting engine for brain failure notifications
_alerting_engine = AlertingEngine()

# Default fallback if symbol lacks optimized data
DEFAULT_SCORE_THRESHOLD = settings.DEFAULT_SCORE_THRESHOLD

# Alias for tests / external imports — the real trade-gating threshold is
# DEFAULT_SCORE_THRESHOLD (0.15) or the per-symbol adaptive threshold.
WINNING_SCORE_THRESHOLD = DEFAULT_SCORE_THRESHOLD

_THRESHOLDS_CACHE = {}
_THRESHOLDS_LAST_LOAD = 0.0


def get_symbol_threshold(symbol: str) -> float:
    """Lazily load and cache the adaptive thresholds JSON generated by the weekly analyzer."""
    global _THRESHOLDS_CACHE, _THRESHOLDS_LAST_LOAD
    now = time.time()
    
    # Reload every 5 minutes to pick up weekly analyzer updates automatically
    if now - _THRESHOLDS_LAST_LOAD > 300:
        thresh_file = os.path.join(os.path.dirname(__file__), '..', '..', 'data', 'adaptive_thresholds.json')
        if os.path.exists(thresh_file):
            try:
                with open(thresh_file) as f:
                    _THRESHOLDS_CACHE = json.load(f)
            except Exception as e:
                logger.warning(f"Failed to load adaptive thresholds: {e}")
        _THRESHOLDS_LAST_LOAD = now
        
    return float(_THRESHOLDS_CACHE.get(symbol, DEFAULT_SCORE_THRESHOLD))

# Process-wide adaptive meta-learner singleton. Loaded lazily and fail-safe:
# any construction/load error leaves the committee on its classic behavior.
_META_LEARNER: AdaptiveMetaLearner | None = None


def get_meta_learner() -> AdaptiveMetaLearner | None:
    """Return the cached adaptive learner, constructing it lazily (fail-safe)."""
    global _META_LEARNER
    if _META_LEARNER is None:
        try:
            _META_LEARNER = AdaptiveMetaLearner(
                state_path=settings.ADAPTIVE_STATE_PATH,
                learning_rate=settings.ADAPTIVE_LEARNING_RATE,
                min_weight=settings.ADAPTIVE_MIN_WEIGHT,
                max_weight=settings.ADAPTIVE_MAX_WEIGHT,
            )
        except Exception as e:  # pragma: no cover - defensive
            logger.warning(f"Adaptive meta-learner unavailable, using classic committee: {e}")
            _META_LEARNER = None
    return _META_LEARNER


def reset_meta_learner() -> None:
    """Drop the cached learner so the next call reloads from current settings/state.

    Primarily used by tests and after out-of-band state updates.
    """
    global _META_LEARNER
    _META_LEARNER = None

# Dynamic Weight Matrix based on Market Regime
REGIME_WEIGHT_MATRIX = {
    "bull": {
        "transformer": 0.40,
        "quant": 0.20,
        "momentum": 0.30,
        "sentinel": 0.05,
        "llm": 0.05
    },
    "bear": {
        "transformer": 0.40,
        "quant": 0.20,
        "momentum": 0.30,
        "sentinel": 0.05,
        "llm": 0.05
    },
    "trending": {
        "transformer": 0.40,
        "quant": 0.20,
        "momentum": 0.30,
        "sentinel": 0.05,
        "llm": 0.05
    },
    "sideways": {
        "transformer": 0.30,
        "quant": 0.20,
        "momentum": 0.10,
        "sentinel": 0.15,
        "llm": 0.25
    },
    "high_volatility": {
        "transformer": 0.15,
        "quant": 0.15,
        "momentum": 0.20,
        "sentinel": 0.40,
        "llm": 0.10
    },
    "low_volatility": {
        "transformer": 0.30,
        "quant": 0.30,
        "momentum": 0.10,
        "sentinel": 0.05,
        "llm": 0.25
    },
    "neutral": {
        "transformer": 0.35,
        "quant": 0.25,
        "momentum": 0.20,
        "sentinel": 0.10,
        "llm": 0.10
    },
    "default": {
        "transformer": 0.35,
        "quant": 0.25,
        "momentum": 0.20,
        "sentinel": 0.10,
        "llm": 0.10
    }
}

def calculate_vote_entropy(votes: list[BrainVote]) -> float:
    """Calculates Shannon Entropy across brain actions to measure consensus conflict."""
    actions = [v.action for v in votes if v.action not in ["stand_aside", "skip"]]
    if not actions:
        return 0.0
    
    counts = defaultdict(int)
    for a in actions:
        counts[a] += 1
        
    entropy = 0.0
    total = len(actions)
    for count in counts.values():
        p = count / total
        entropy -= p * math.log2(p)
        
    return entropy

def calculate_confidence_size_multiplier(score: float, entropy: float, threshold: float) -> float:
    """Calculates dynamic position sizing multiplier based on committee conviction score.
    
    Formula:
    - Base score threshold: symbol's adaptive threshold
    - Multiplier ranges from 0.50x (marginal confidence) to 1.75x (unanimous conviction).
    - High vote entropy (>0.8) penalizes multiplier by up to 25%.
    """
    if score < threshold:
        return 0.0
    
    # Linear scale from threshold score -> 0.50x to 1.00 score -> 1.75x
    # Prevent division by zero if threshold somehow is 1.0
    denom = (1.0 - threshold) if threshold < 1.0 else 0.01
    normalized_score = (score - threshold) / denom
    base_mult = 0.50 + normalized_score * 1.25  # 0.50 to 1.75
    
    # Entropy penalty for vote conflict
    if entropy > 0.5:
        penalty = min((entropy - 0.5) * 0.30, 0.25)
        base_mult *= (1.0 - penalty)
        
    return max(0.40, min(1.75, round(base_mult, 2)))

async def run_committee(symbol: str, price: float, signal: dict[str, Any]) -> CommitteeResult:
    """Runs the 5-brain ensemble committee with dynamic weighting and confidence position sizing.
    
    Returns:
        CommitteeResult containing final action, weighted score, size_multiplier, and vote audit logs.
    """
    import time as _time
    _t0 = _time.monotonic()

    regime = signal.get("regime", "default")
    
    # Check for hard exits (Stop Loss / Take Profit) BEFORE voting
    if signal.get("action") == "close":
        result = CommitteeResult(
            action="close",
            score=1.0,
            size_multiplier=0.0,
            entropy=0.0,
            votes=[],
            active_weights={},
            explanation=signal.get("reason", "Price-based exit condition")
        )
        try:
            from src.metrics import record_committee_latency
            record_committee_latency(symbol, _time.monotonic() - _t0)
        except Exception:
            pass
        return result
        
    weights = REGIME_WEIGHT_MATRIX.get(regime, REGIME_WEIGHT_MATRIX["default"])
    symbol_threshold = get_symbol_threshold(symbol)

    # Run all 5 brains concurrently (transformer_brain uses asyncio.to_thread + network I/O,
    # so running sequentially would serialize its latency before every other brain).
    raw_results = await asyncio.gather(
        transformer_brain(symbol, price, signal),
        quant_brain(symbol, price, signal),
        momentum_brain(symbol, price, signal),
        sentinel_brain(symbol, price, signal),
        llm_brain(symbol, price, signal),
        return_exceptions=True
    )
    
    # Filter out exceptions and log failures
    raw_votes = []
    for i, result in enumerate(raw_results):
        brain_names = ["transformer", "quant", "momentum", "sentinel", "llm"]
        if isinstance(result, Exception):
            brain_name = brain_names[i]
            logger.warning(f"Brain '{brain_name}' failed: {result}. Using fallback.")
            # Alert on brain failure
            await _alerting_engine.check_brain_failure_alert(brain_name, str(result))
            # Create a fallback vote for failed brain
            fallback_vote = BrainVote(
                name=brain_names[i],
                action="stand_aside",
                confidence=0.0,
                weight=0.0,
                regime=signal.get("regime", "default"),
                reason=f"Brain failed: {result}",
                is_veto=False
            )
            raw_votes.append(fallback_vote)
        else:
            raw_votes.append(result)

    # Re-weight votes dynamically based on active regime matrix
    votes = []
    for v in raw_votes:
        w = weights.get(v.name, v.weight)
        votes.append(BrainVote(
            name=v.name,
            action=v.action,
            confidence=v.confidence,
            weight=w,
            regime=v.regime,
            reason=v.reason,
            is_veto=v.is_veto,
            tensor_state=getattr(v, "tensor_state", None)
        ))

    # Check for hard vetoes (Sentinel / Crash)
    for v in votes:
        if v.is_veto or (v.name == "sentinel" and v.action == "stand_aside" and v.confidence >= 0.85):
            return CommitteeResult(
                action="stand_aside",
                score=0.0,
                size_multiplier=0.0,
                entropy=0.0,
                votes=votes,
                active_weights=weights,
                vetoed=True,
                veto_reason=v.reason
            )

    entropy = calculate_vote_entropy(votes)
    decision_id = uuid.uuid4().hex

    # ── Classic (baseline) weighted score per action ──
    scores = defaultdict(float)
    active_weight = 0.0
    for v in votes:
        if v.action not in ["stand_aside", "skip", "hold"]:
            scores[v.action] += v.confidence * v.weight
        if v.action not in ["stand_aside", "skip"]:
            active_weight += v.weight

    if active_weight > 0:
        for action in scores:
            scores[action] /= active_weight

    if scores:
        baseline_winner = max(scores, key=scores.get)
        baseline_score = scores[baseline_winner]
    else:
        baseline_winner, baseline_score = "stand_aside", 0.0

    # ── Shared Decision Source Gate (Step 4: Structural Fix) ──
    # ALL decision sources must pass through check_decision_source_gate()
    # This eliminates the bug class where new fallback sources bypass validation.
    adaptive_used = False
    adaptive_weights: dict[str, float] = {}
    explanation: str | None = None
    winner, score = baseline_winner, baseline_score

    # Always compute adaptive weights for shadow mode observability
    learner = get_meta_learner()
    shadow_decision = None
    if learner is not None:
        try:
            shadow_decision = learner.combine(raw_votes, regime)
            adaptive_weights = shadow_decision.weights
            explanation = shadow_decision.explanation
        except Exception as e:
            logger.warning(f"Adaptive combine failed: {e}")

    # Source 1: Mathematical Adaptive Learner
    adaptive_gate = check_decision_source_gate("adaptive_learner", regime)
    if adaptive_gate.allowed and shadow_decision:
        adaptive_used = True
        winner, score = shadow_decision.action, shadow_decision.confidence
        logger.info(f"Adaptive learner ACTIVE for regime '{regime}' (gate: {adaptive_gate.reason})")
    elif learner is not None and settings.ADAPTIVE_ML_ENABLED:
        logger.info(f"Adaptive learner SHADOW for regime '{regime}' (gate: {adaptive_gate.reason})")

    # Source 2: RL Meta-Learner (PPO) — fallback if adaptive not used
    if not adaptive_used:
        ppo_gate = check_decision_source_gate("ppo", regime)
        rl_learner = RLMetaLearner()
        if ppo_gate.allowed and getattr(rl_learner, "model", None) and signal.get("backtest_df") is None:
            try:
                features = signal.get("features", {})
                features["rsi"] = signal.get("rsi", 50.0)
                features["atr"] = signal.get("atr", 0.0)
                features["macd"] = signal.get("macd", 0.0)
                
                decision = rl_learner.combine(raw_votes, regime, features)
                adaptive_weights = decision.weights
                explanation = decision.explanation
                adaptive_used = True
                winner, score = decision.action, decision.confidence
                logger.info(f"PPO RL Meta-Learner ACTIVE for regime '{regime}' (gate: {ppo_gate.reason})")
            except Exception as e:
                logger.warning(f"RL Meta-Learner combine failed: {e}")
        elif settings.ADAPTIVE_ML_ENABLED:
            logger.info(f"PPO SHADOW for regime '{regime}' (gate: {ppo_gate.reason})")

    # Source 3: Decision Transformer — fallback if PPO not used
    if not adaptive_used:
        dt_gate = check_decision_source_gate("decision_transformer", regime)
        if dt_gate.allowed and signal.get("backtest_df") is None:
            try:
                regime_targets = {
                    "trending": 3.0, "bull": 3.0, "bear": 3.0,
                    "sideways": 1.5, "mean_reverting": 1.5,
                    "high_volatility": 2.5, "low_volatility": 1.0,
                    "neutral": 2.0
                }
                target_return = regime_targets.get(regime, 2.0)
                
                dt_decision = await run_decision_transformer(symbol, price, signal, target_return)
                if dt_decision is not None:
                    adaptive_used = True
                    adaptive_weights = dt_decision.adaptive_weights
                    explanation = dt_decision.explanation
                    winner, score = dt_decision.action, dt_decision.score
                    if hasattr(dt_decision, 'size_multiplier') and dt_decision.size_multiplier > 0:
                        size_mult = dt_decision.size_multiplier
                    logger.info(f"Decision Transformer ACTIVE for regime '{regime}' (gate: {dt_gate.reason}, target_return={target_return}%)")
            except Exception as e:
                logger.warning(f"Decision Transformer combine failed: {e}")
        elif settings.ADAPTIVE_ML_ENABLED:
            logger.info(f"Decision Transformer SHADOW for regime '{regime}' (gate: {dt_gate.reason})")

    # Source 4: Hierarchical Skills — fallback if DT not used
    if not adaptive_used:
        skills_gate = check_decision_source_gate("hierarchical_skills", regime)
        if skills_gate.allowed and signal.get("backtest_df") is None:
            try:
                from src.committee.hierarchical_skills import run_hierarchical_skills
                skills_decision = await run_hierarchical_skills(symbol, price, signal)
                if skills_decision is not None:
                    adaptive_used = True
                    adaptive_weights = getattr(skills_decision, 'adaptive_weights', {})
                    explanation = getattr(skills_decision, 'explanation', '')
                    winner, score = skills_decision.action, skills_decision.score
                    logger.info(f"Hierarchical Skills ACTIVE for regime '{regime}' (gate: {skills_gate.reason})")
            except Exception as e:
                logger.warning(f"Hierarchical Skills combine failed: {e}")
        elif settings.ADAPTIVE_ML_ENABLED:
            logger.info(f"Hierarchical Skills SHADOW for regime '{regime}' (gate: {skills_gate.reason})")

    # Threshold + confidence sizing apply identically regardless of source.
    # In sideways/choppy markets, use a lower threshold so the committee
    # doesn't stand aside on every marginal signal. The adaptive learner
    # will learn whether these trades actually work.
    effective_threshold = symbol_threshold
    if regime in ("sideways", "low_volatility", "neutral"):
        effective_threshold = max(0.10, symbol_threshold * 0.5)
    
    if not scores and not adaptive_used:
        return CommitteeResult(
            action="stand_aside",
            score=0.0,
            size_multiplier=0.0,
            entropy=entropy,
            votes=votes,
            active_weights=weights,
            decision_id=decision_id,
            adaptive_used=adaptive_used,
            adaptive_weights=adaptive_weights,
            explanation=explanation,
        )

    if score < effective_threshold or winner in ["stand_aside", "skip"]:
        final_action = "stand_aside"
        size_mult = 0.0
    else:
        final_action = winner
        size_mult = calculate_confidence_size_multiplier(score, entropy, effective_threshold)

    result = CommitteeResult(
        action=final_action,
        score=score,
        size_multiplier=size_mult,
        entropy=entropy,
        votes=votes,
        active_weights=weights,
        decision_id=decision_id,
        adaptive_used=adaptive_used,
        adaptive_weights=adaptive_weights,
        explanation=explanation,
    )

    # OOD Discriminator check — override if state is out-of-distribution
    try:
        ood_disc = get_ood_discriminator()
        if ood_disc is not None and ood_disc._is_trained:
            # Build signal dict for OOD check
            ood_signal = {
                "regime": signal.get("regime", "default"),
                "features": signal.get("features", {}),
                "votes": signal.get("votes", []),
            }
            result = check_ood_and_override(symbol, price, ood_signal, result, ood_disc)
    except Exception as e:
        logger.warning(f"OOD check failed for {symbol}: {e}")

    # Publish Prometheus metrics (best-effort, never blocks trading)
    try:
        from src.metrics import record_committee_latency, record_committee_weights
        record_committee_latency(symbol, _time.monotonic() - _t0)
        record_committee_weights(symbol, result.votes, result.action, result.score)
    except Exception:
        pass

    return result
