"""Main trading bot implementation."""

import asyncio
import time
from datetime import datetime, timezone
from typing import Dict, Any, Optional

from src.config import settings
from src.logging_config import get_logger
from src.db import init_db
from src.exchange import AlpacaExchange
from src.api import start_fastapi_server_async
from src.strategies import TradingStrategy
from src.risk import RiskManager
from src.telegram_alerts import send_telegram_alert

logger = get_logger("bot")


async def _record_committee_outcome(symbol: str, exit_price: float, exit_reason: Optional[str] = None) -> None:
    """On position exit, close the open decision snapshot and update the learner.

    Fully fail-safe: realized-PnL bookkeeping for the adaptive layer must never
    interfere with trading. risk.py stays authoritative for the exit itself.
    """
    try:
        from datetime import datetime, timezone
        from src.db import get_open_snapshot, close_decision_snapshot
        from src.committee.committee import get_meta_learner
        from src.metrics import update_adaptive_metrics, alert_weight_change

        snap = get_open_snapshot(symbol)
        if not snap:
            return

        entry_price = float(snap.get("entry_price", 0.0))
        qty = float(snap.get("qty", 0.0))
        action = snap.get("final_action", "buy")
        if entry_price <= 0 or qty == 0:
            return

        if action == "buy":
            realized_pnl = (exit_price - entry_price) * qty
            return_pct = (exit_price - entry_price) / entry_price * 100.0
        else:  # sell / short
            realized_pnl = (entry_price - exit_price) * qty
            return_pct = (entry_price - exit_price) / entry_price * 100.0

        holding_sec = 0.0
        created = snap.get("created_at")
        if created:
            try:
                started = datetime.fromisoformat(str(created).replace("Z", "+00:00"))
                holding_sec = max(0.0, (datetime.now(timezone.utc) - started).total_seconds())
            except Exception:
                pass

        max_fav_pct = 0.0
        max_adv_pct = 0.0
        global strategy
        if strategy is not None and hasattr(strategy, '_trailing_peaks') and symbol in strategy._trailing_peaks:
            peak = strategy._trailing_peaks[symbol]
            if action == "buy":
                max_fav_pct = (peak - entry_price) / entry_price * 100.0 if peak > entry_price else 0.0
            else:
                max_fav_pct = (entry_price - peak) / entry_price * 100.0 if peak < entry_price else 0.0

        close_decision_snapshot(
            snap["decision_id"],
            realized_pnl=realized_pnl,
            return_pct=return_pct,
            holding_period_sec=holding_sec,
            exit_reason=exit_reason,
            max_favorable_pct=max_fav_pct,
            max_adverse_pct=max_adv_pct,
        )

        learner = get_meta_learner()
        if learner is not None:
            report = learner.update(
                {
                    "regime": snap.get("regime", "default"),
                    "final_action": action,
                    "brain_votes": snap.get("brain_votes", {}),
                },
                {"net_pnl": realized_pnl, "return_pct": return_pct},
            )
            update_adaptive_metrics(learner.snapshot())
            if report.material_change:
                await alert_weight_change(
                    report.regime, report.old_weights, report.new_weights, learner.sample_count
                )
                
        # Update strategy learner
        selected_strategy = snap.get("feature_snapshot", {}).get("selected_strategy")
        if selected_strategy:
            from src.strategy_selector import record_strategy_outcome
            record_strategy_outcome(
                regime=snap.get("regime", "default"),
                strategy_name=selected_strategy,
                pnl=realized_pnl,
                return_pct=return_pct
            )

    except Exception as e:
        logger.error(f"Adaptive outcome recording failed for {symbol} (non-fatal): {e}")


# Global state
ex: Optional[AlpacaExchange] = None
strategy: Optional[TradingStrategy] = None
risk_manager: Optional[RiskManager] = None

import json

def read_regime_flag():
    """Read the regime flag file. Returns a dict with pause flags."""
    default = {
        "pause_grok": False,
        "pause_oracle": False,
        "grok_multiplier": 1.0,
        "oracle_multiplier": 1.0,
        "regime": "normal"
    }
    try:
        with open(r"C:\Users\brian\OneDrive\Documents\Static-Repo-okx-bot\regime_flag.txt", "r") as f:
            data = json.load(f)
            return data
    except (FileNotFoundError, json.JSONDecodeError):
        return default

def get_banned_symbols():
    """Read the banned symbols list generated by the weekly analyzer."""
    try:
        import os
        ban_file = os.path.join(os.path.dirname(__file__), '..', 'data', 'banned_symbols.json')
        if os.path.exists(ban_file):
            with open(ban_file, 'r') as f:
                bans = json.load(f)
                return {b["symbol"] for b in bans}
    except Exception as e:
        logger.warning(f"Failed to read banned symbols: {e}")
    return set()

async def process_signal_for_symbol(symbol: str, current_price: float, risk_manager: RiskManager, strategy: TradingStrategy, ex: AlpacaExchange) -> None:
    """Processes signal for a single symbol asynchronously."""
    try:
        # Get current positions
        positions = await ex.get_positions()
        position_dict = {p["symbol"].replace("/", ""): p for p in positions}
        current_position = position_dict.get(symbol.replace("/", ""))

        # Trailing Stop Check
        if current_position:
            avg_entry_price = float(current_position.get("avg_entry_price", 0))
            qty = float(current_position.get("qty", 0))
            trailing_action = risk_manager.check_trailing_stop(symbol, current_price, avg_entry_price, qty)
            
            if trailing_action == "close":
                side = "sell" if qty > 0 else "buy"
                qty_abs = abs(qty)
                order_result = await ex.create_order(
                    symbol=symbol,
                    qty=qty_abs,
                    side=side,
                    type="market"
                )
                logger.info(f"Trailing Stop Executed: {symbol}")
                await send_telegram_alert(f"🚨 <b>Trailing Stop Triggered</b>\nSymbol: {symbol}\nClosed {qty} @ ${current_price:.2f}")
                await _record_committee_outcome(symbol, current_price, exit_reason="trailing_stop")
                return  # Skip standard signals

        # Generate trading signal
        signal = await strategy.generate_trading_signal(
            symbol,
            current_price,
            current_position
        )

        logger.info(f"Signal for {symbol} @ ${current_price:.2f}: {signal['action']} (regime: {signal['regime']}, RSI: {signal['rsi']:.2f})")

        # ── 5-BRAIN ENSEMBLE COMMITTEE EVALUATION ──
        from src.committee.committee import run_committee
        committee_result = await run_committee(symbol, current_price, signal)

        # Log committee votes breakdown
        logger.info(f"🗳️ Committee evaluation for {symbol}:")
        for v in committee_result.votes:
            logger.info(
                f"   [{v.name:<11}] {v.action.upper():<11} "
                f"conf={v.confidence:.3f} (weight={v.weight*100:.0f}%) "
                f"| {v.reason}"
            )

        if committee_result.vetoed:
            logger.info(f"🛑 {symbol} trade VETOED by Committee: {committee_result.veto_reason}")
            return

        logger.info(f"   Winner: {committee_result.action.upper()} score={committee_result.score:.3f} (threshold >= 0.60)")

        if committee_result.action in ["stand_aside", "skip", "hold"]:
            logger.info(f"⏭️ {symbol}: Committee action is {committee_result.action.upper()} (score={committee_result.score:.3f}). Skipping trade entry.")
            return

        # Override original signal action & confidence with committee's consensus decision
        signal["action"] = committee_result.action
        signal["confidence"] = committee_result.score

        if signal["action"] in ["buy", "sell"]:
            # ── REGIME SWITCH CHECK (Only for ENTRY, not EXIT) ──
            if signal["action"] == "buy":
                regime_flag = read_regime_flag()
                if regime_flag.get("pause_oracle", False):
                    logger.info(f"⏸️ Oracle paused by Regime Switch (Quiet market). Skipping entry for {symbol}.")
                    return

            # ── BANNED SYMBOLS CHECK ──
            banned = get_banned_symbols()
            if symbol in banned:
                logger.info(f"🚫 {symbol} is currently BANNED due to poor performance. Skipping entry.")
                return

            # Check position limit before entering
            risk_status = await risk_manager.update_account_status()
            if risk_status["status"] == "position_limit_exceeded":
                logger.warning(f"Skipping entry for {symbol}: position limit reached")
                return
            if risk_status["status"] == "exposure_limit_exceeded":
                logger.warning(f"Skipping entry for {symbol}: exposure cap reached")
                return

            # Calculate position size
            position_size, sizing_status = risk_manager.calculate_position_size(
                symbol,
                current_price,
                signal["regime"],
                atr=signal.get("atr"),
                confidence=signal.get("confidence", 1.0)
            )

            if sizing_status != "ok":
                logger.warning(f"Position sizing failed for {symbol}: {sizing_status}")
                return
                
            # Apply Regime Switch Multiplier if buying
            if signal["action"] == "buy":
                multiplier = regime_flag.get("oracle_multiplier", 1.0)
                position_size = position_size * multiplier

            # Apply Committee Confidence Sizing Multiplier (Higher confidence = Larger trade size)
            committee_mult = getattr(committee_result, "size_multiplier", 1.0)
            position_size = position_size * committee_mult
            position_size = round(position_size, 6)
            logger.info(f"📊 Applied Committee Sizing Multiplier ({committee_mult:.2f}x based on score {committee_result.score:.2f}) → Final Qty: {position_size}")

            # Place order
            order_result = await ex.create_order(
                symbol=symbol,
                qty=position_size,
                side=signal["action"],
                type="market"
            )

            logger.info(f"Order executed: {signal['action']} {position_size} {symbol} @ ${current_price:.2f}")
            logger.debug(f"Order result: {order_result}")
            await send_telegram_alert(f"📈 <b>Order Executed</b>\nSymbol: {symbol}\nAction: {signal['action'].upper()}\nQty: {position_size}\nPrice: ${current_price:.2f}")

            # Persist committee decision snapshot for the adaptive meta-learner
            # (fail-safe; closed out with realized PnL when the position exits).
            try:
                from src.db import save_decision_snapshot
                save_decision_snapshot(
                    decision_id=committee_result.decision_id,
                    symbol=symbol,
                    regime=signal.get("regime", "default"),
                    final_action=signal["action"],
                    confidence=committee_result.score,
                    size_multiplier=getattr(committee_result, "size_multiplier", 1.0),
                    entry_price=current_price,
                    qty=position_size,
                    brain_votes={v.name: v.action for v in committee_result.votes},
                    feature_snapshot_json=json.dumps({
                        "atr": signal.get("atr"),
                        "rsi": signal.get("rsi"),
                        "macd": signal.get("macd"),
                        "selected_strategy": signal.get("selected_strategy"),
                    }),
                    causal_reasoning_json=json.dumps({
                        v.name: getattr(v, "causal_reasoning", None) 
                        for v in committee_result.votes if getattr(v, "causal_reasoning", None)
                    })
                )
            except Exception as db_e:
                logger.warning(f"Decision snapshot persist failed for {symbol} (non-fatal): {db_e}")

        elif signal["action"] == "close" and current_position:

            # Close existing position
            qty = float(current_position["qty"])
            side = "sell" if qty > 0 else "buy"
            qty_abs = abs(qty)

            order_result = await ex.create_order(
                symbol=symbol,
                qty=qty_abs,
                side=side,
                type="market"
            )

            logger.info(f"Position closed: {symbol} (was {qty}) - reason: {signal.get('reason', 'unknown')}")
            logger.debug(f"Close order result: {order_result}")
            await send_telegram_alert(f"📉 <b>Position Closed</b>\nSymbol: {symbol}\nReason: {signal.get('reason', 'unknown')}")
            await _record_committee_outcome(symbol, current_price, exit_reason=signal.get('reason', 'unknown'))

    except Exception as e:
        logger.error(f"Error processing {symbol}: {e}")


async def monitor_killswitch(risk_manager: RiskManager) -> None:
    """Background task to monitor killswitch continuously."""
    import os
    while True:
        try:
            if await risk_manager.check_killswitch_conditions():
                logger.critical("KILLSWITCH ACTIVATED - Liquidating all positions")
                await send_telegram_alert(f"💀 <b>KILLSWITCH ACTIVATED</b>\nLiquidating all positions immediately.")
                await risk_manager.liquidate_all_positions()
                os._exit(1)
            await asyncio.sleep(10)
        except Exception as e:
            logger.error(f"Killswitch monitor error: {e}")
            await asyncio.sleep(10)


async def run_periodic_analyzer() -> None:
    """Background task to run the analyzer script periodically."""
    import sys
    import os
    script_path = os.path.join(os.path.dirname(__file__), '..', 'scripts', 'weekly_analyzer.py')
    
    while True:
        try:
            logger.info("Running periodic analyzer script...")
            process = await asyncio.create_subprocess_exec(
                sys.executable, script_path,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            stdout, stderr = await process.communicate()
            
            if process.returncode == 0:
                logger.info(f"Analyzer completed successfully:\n{stdout.decode().strip()}")
            else:
                logger.error(f"Analyzer failed with code {process.returncode}:\n{stderr.decode().strip()}")
                
        except Exception as e:
            logger.error(f"Error running periodic analyzer: {e}")
            
        # Run every 12 hours
        await asyncio.sleep(12 * 3600)

async def run_periodic_automl() -> None:
    """Background task to run the AutoML pipeline every Saturday night."""
    import sys
    import os
    from datetime import datetime, timedelta
    
    script_path = os.path.join(os.path.dirname(__file__), '..', 'scripts', 'automl_pipeline.py')
    
    while True:
        try:
            now = datetime.now()
            # Calculate days until Saturday (5 = Saturday)
            days_ahead = 5 - now.weekday()
            if days_ahead < 0 or (days_ahead == 0 and now.hour >= 2):
                days_ahead += 7
            
            # Target 2 AM on Saturday
            target_time = now + timedelta(days=days_ahead)
            target_time = target_time.replace(hour=2, minute=0, second=0, microsecond=0)
            
            sleep_seconds = (target_time - now).total_seconds()
            logger.info(f"AutoML pipeline scheduled for {target_time} (in {sleep_seconds/3600:.1f} hours)")
            
            await asyncio.sleep(sleep_seconds)
            
            logger.info("Running AutoML pipeline...")
            process = await asyncio.create_subprocess_exec(
                sys.executable, script_path,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            stdout, stderr = await process.communicate()
            
            if process.returncode == 0:
                logger.info(f"AutoML pipeline completed successfully:\n{stdout.decode().strip()}")
            else:
                logger.error(f"AutoML pipeline failed with code {process.returncode}:\n{stderr.decode().strip()}")
                
        except Exception as e:
            logger.error(f"Error running AutoML pipeline: {e}")
            await asyncio.sleep(3600)

async def run_periodic_cull() -> None:
    """Background task to run the Evolution Cull on the 1st of every month."""
    import sys
    import os
    from datetime import datetime
    
    script_path = os.path.join(os.path.dirname(__file__), '..', 'scripts', 'evolution_cull.py')
    
    while True:
        try:
            now = datetime.now()
            # Calculate time until 1st of next month at 4 AM
            if now.month == 12:
                target_month = 1
                target_year = now.year + 1
            else:
                target_month = now.month + 1
                target_year = now.year
                
            target_time = datetime(target_year, target_month, 1, 4, 0, 0)
            
            sleep_seconds = (target_time - now).total_seconds()
            logger.info(f"Evolution Cull scheduled for {target_time} (in {sleep_seconds/86400:.1f} days)")
            
            await asyncio.sleep(sleep_seconds)
            
            logger.info("Running Evolution Cull pipeline...")
            process = await asyncio.create_subprocess_exec(
                sys.executable, script_path,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            stdout, stderr = await process.communicate()
            
            if process.returncode == 0:
                logger.info(f"Evolution Cull completed successfully:\n{stdout.decode().strip()}")
            else:
                logger.error(f"Evolution Cull failed with code {process.returncode}:\n{stderr.decode().strip()}")
                
        except Exception as e:
            logger.error(f"Error running Evolution Cull: {e}")
            await asyncio.sleep(86400)

async def run_periodic_research() -> None:
    """Background task to run the Automatic Researcher every Sunday morning."""
    import sys
    import os
    from datetime import datetime, timedelta
    
    script_path = os.path.join(os.path.dirname(__file__), '..', 'scripts', 'automatic_researcher.py')
    
    while True:
        try:
            now = datetime.now()
            # Calculate days until Sunday (6 = Sunday)
            days_ahead = 6 - now.weekday()
            if days_ahead < 0 or (days_ahead == 0 and now.hour >= 4):
                days_ahead += 7
                
            # Target 4 AM on Sunday
            target_time = now + timedelta(days=days_ahead)
            target_time = target_time.replace(hour=4, minute=0, second=0, microsecond=0)
            
            sleep_seconds = (target_time - now).total_seconds()
            logger.info(f"Automatic Research scheduled for {target_time} (in {sleep_seconds/3600:.1f} hours)")
            
            await asyncio.sleep(sleep_seconds)
            
            logger.info("Running Automatic Research...")
            process = await asyncio.create_subprocess_exec(
                sys.executable, script_path,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            stdout, stderr = await process.communicate()
            
            if process.returncode == 0:
                logger.info(f"Automatic Research completed successfully:\n{stdout.decode().strip()}")
            else:
                logger.error(f"Automatic Research failed with code {process.returncode}:\n{stderr.decode().strip()}")
                
        except Exception as e:
            logger.error(f"Error running Automatic Research: {e}")
            await asyncio.sleep(3600)

async def run_periodic_post_mortem() -> None:
    """Background task to run the Post-Mortem AI every Saturday morning."""
    import sys
    import os
    from datetime import datetime, timedelta
    
    script_path = os.path.join(os.path.dirname(__file__), '..', 'scripts', 'post_mortem.py')
    
    while True:
        try:
            now = datetime.now()
            # Calculate days until Saturday (5 = Saturday)
            days_ahead = 5 - now.weekday()
            if days_ahead < 0 or (days_ahead == 0 and now.hour >= 4):
                days_ahead += 7
                
            # Target 4 AM on Saturday
            target_time = now + timedelta(days=days_ahead)
            target_time = target_time.replace(hour=4, minute=0, second=0, microsecond=0)
            
            sleep_seconds = (target_time - now).total_seconds()
            logger.info(f"Post-Mortem AI scheduled for {target_time} (in {sleep_seconds/3600:.1f} hours)")
            
            await asyncio.sleep(sleep_seconds)
            
            logger.info("Running Post-Mortem AI...")
            process = await asyncio.create_subprocess_exec(
                sys.executable, script_path,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            stdout, stderr = await process.communicate()
            
            if process.returncode == 0:
                logger.info(f"Post-Mortem AI completed successfully:\n{stdout.decode().strip()}")
            else:
                logger.error(f"Post-Mortem AI failed with code {process.returncode}:\n{stderr.decode().strip()}")
                
        except Exception as e:
            logger.error(f"Error running Post-Mortem AI: {e}")
            await asyncio.sleep(3600)

async def run_trading_bot() -> None:
    """Main trading bot loop."""
    global ex

    try:
        logger.info("Initializing Apex Oracle Bot v2.0.0")
        logger.info("=================================")
        logger.info("Configuration:")
        logger.info(f"Bot Name: {settings.BOT_NAME}")
        logger.info(f"Database: {settings.DATABASE_URL}")
        logger.info(f"Exchange: Alpaca Crypto (Paper={settings.ALPACA_BASE_URL.endswith('paper-api.alpaca.markets')})")
        logger.info(f"Symbols: {settings.SYMBOLS}")
        logger.info("=================================")

        # Initialize database (handle connection failures gracefully)
        try:
            init_db()
            logger.info("Database connected successfully")
        except Exception as e:
            logger.warning(f"Database connection failed (will retry later): {e}")
            logger.info("Running in offline mode - some features may be limited")

        logger.info(settings.log_config())

        # Initialize exchange
        ex = AlpacaExchange()
        try:
            await ex.load()
            logger.info("Alpaca exchange connected")
        except RuntimeError:
            # Re-raise configuration and auth errors which are fatal
            raise
        except Exception as e:
            logger.warning(f"Alpaca exchange connection failed on startup: {e}. Bot will start in offline/retry mode.")

        # Initialize trading strategy and risk manager
        strategy = TradingStrategy(ex)
        risk_manager = RiskManager(ex)
        logger.info("Trading strategy and risk manager initialized")

        # Start API server
        await start_fastapi_server_async()
        logger.info("FastAPI server started")

        # Start Killswitch monitor
        active_tasks: set[asyncio.Task] = set()
        ks_task = asyncio.create_task(monitor_killswitch(risk_manager))
        active_tasks.add(ks_task)
        ks_task.add_done_callback(active_tasks.discard)
        logger.info("Killswitch monitor started")

        # Start periodic analyzer
        analyzer_task = asyncio.create_task(run_periodic_analyzer())
        active_tasks.add(analyzer_task)
        analyzer_task.add_done_callback(active_tasks.discard)
        logger.info("Periodic analyzer task started")

        # Start periodic AutoML pipeline
        automl_task = asyncio.create_task(run_periodic_automl())
        active_tasks.add(automl_task)
        automl_task.add_done_callback(active_tasks.discard)
        logger.info("Periodic AutoML pipeline task started")

        # Start periodic Evolution Cull
        cull_task = asyncio.create_task(run_periodic_cull())
        active_tasks.add(cull_task)
        cull_task.add_done_callback(active_tasks.discard)
        logger.info("Periodic Evolution Cull task started")

        # Start periodic Automatic Research
        research_task = asyncio.create_task(run_periodic_research())
        active_tasks.add(research_task)
        research_task.add_done_callback(active_tasks.discard)
        logger.info("Periodic Automatic Research task started")

        # Start periodic Post-Mortem AI
        post_mortem_task = asyncio.create_task(run_periodic_post_mortem())
        active_tasks.add(post_mortem_task)
        post_mortem_task.add_done_callback(active_tasks.discard)
        logger.info("Periodic Post-Mortem AI task started")

        # Main trading loop
        logger.info("Bot initialization complete. Starting event-driven trading loop.")

        last_eval_time = {s: 0.0 for s in settings.SYMBOLS}

        try:
            async for bar_msg in ex.listen_crypto_bars(settings.SYMBOLS):
                symbol = bar_msg.get("S")
                current_price = float(bar_msg.get("c"))
                
                # Throttle evaluation to LOOP_INTERVAL_SEC to avoid REST rate limits on get_bars/get_positions
                now = time.time()
                if now - last_eval_time.get(symbol, 0) < settings.LOOP_INTERVAL_SEC:
                    continue
                last_eval_time[symbol] = now

                # Dispatch signal processing to a background task so it doesn't block the WebSocket stream
                task = asyncio.create_task(process_signal_for_symbol(symbol, current_price, risk_manager, strategy, ex))
                active_tasks.add(task)
                task.add_done_callback(active_tasks.discard)

        except Exception as e:
            logger.error(f"WebSocket stream error: {e}")
            await asyncio.sleep(5)

    except KeyboardInterrupt:
        logger.info("Shutdown requested. Exiting gracefully.")
    except Exception as e:
        logger.error(f"Fatal error in bot: {e}", exc_info=True)
        raise
    finally:
        logger.info("Cleaning up background tasks and closing exchange...")
        for task in list(active_tasks):
            from src.committee.transformer_brain import transformer_brain
            from src.committee.quant_brain import quant_brain
            from src.committee.momentum_brain import momentum_brain
            from src.committee.sentinel_brain import sentinel_brain
            from src.committee.llm_brain import llm_brain
            from src.committee.adaptive_meta import AdaptiveMetaLearner
            from src.committee.rl_meta import RLMetaLearner

            from scripts.post_mortem import analyze_losses

            # Global meta-learners
            adaptive_learner = AdaptiveMetaLearner(state_path="data/adaptive_state.json")
            rl_learner = RLMetaLearner()

            async def evaluate_committee(symbol: str, current_price: float, signal: Dict[str, Any]) -> CommitteeResult:
                """Run all 5 brains concurrently and return a weighted consensus."""
                # 1. Run inference for all brains concurrently
                tasks = [
                    transformer_brain(symbol, current_price, signal),
                    quant_brain(symbol, current_price, signal),
                    momentum_brain(symbol, current_price, signal),
                    sentinel_brain(symbol, current_price, signal),
                    llm_brain(symbol, current_price, signal),
                ]
                results = await asyncio.gather(*tasks, return_exceptions=True)

                valid_votes = []
                for r in results:
                    if isinstance(r, BrainVote):
                        valid_votes.append(r)
                    else:
                        logger.error(f"Brain failed with exception: {r}")

                if not valid_votes:
                    return CommitteeResult(action="stand_aside", score=0.0)

                # Check for hard vetos
                vetos = [v for v in valid_votes if v.is_veto]
                if vetos:
                    reasons = ", ".join(f"{v.name}: {v.reason}" for v in vetos)
                    return CommitteeResult(action="stand_aside", score=0.0, vetoed=True, veto_reason=reasons)

                regime = signal.get("regime", "default")
                
                # Check if RL model is loaded
                if getattr(rl_learner, "model", None):
                    # Use PPO RL Meta-Learner
                    features = signal.get("features", {})
                    features["rsi"] = signal.get("rsi", 50.0)
                    features["atr"] = signal.get("atr", 0.0)
                    features["macd"] = signal.get("macd", 0.0)
                    decision = rl_learner.combine(valid_votes, regime, features)
                    size_multiplier = getattr(decision, "pos_size_mult", 1.0)
                else:
                    # 2. Use mathematical AdaptiveMetaLearner
                    decision = adaptive_learner.combine(valid_votes, regime)
                    size_multiplier = 1.0

                return CommitteeResult(
                    action=decision.action,
                    score=decision.confidence,
                    size_multiplier=size_multiplier,
                    votes=valid_votes,
                    active_weights=decision.weights,
                    adaptive_used=True,
                    explanation=decision.explanation
                )
            task.cancel()
        if active_tasks:
            await asyncio.gather(*active_tasks, return_exceptions=True)
        if ex:
            await ex.close()
        logger.info("Shutdown complete.")


def run_bot() -> None:
    """Synchronous wrapper for async bot."""
    asyncio.run(run_trading_bot())